---
- name: Check that asdf was installed
  stat:
    path: "{{ asdf_user_home }}/.asdf/bin/asdf"
  register: asdf_install

- name: Assert asdf was installed
  assert:
    that:
      - asdf_install.stat.exists
      - asdf_install.stat.pw_name == asdf_user
    msg: "The asdf repository must exist."
